"""add notified_cancellation to bookings

Revision ID: 05de1ccbf779
Revises: b6a81b2f0ebc
Create Date: 2026-03-16 15:37:47.394041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05de1ccbf779'
down_revision: Union[str, Sequence[str], None] = 'b6a81b2f0ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('notified_cancellation', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'notified_cancellation')
    # ### end Alembic commands ###
