"""add failed_emails table

Revision ID: 25d5ad84efe7
Revises: e8a411535e47
Create Date: 2026-03-07 22:05:14.488430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d5ad84efe7'
down_revision: Union[str, Sequence[str], None] = 'e8a411535e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('email_body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_emails_id'), 'failed_emails', ['id'], unique=False)
    op.create_index(op.f('ix_failed_emails_message_id'), 'failed_emails', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_failed_emails_message_id'), table_name='failed_emails')
    op.drop_index(op.f('ix_failed_emails_id'), table_name='failed_emails')
    op.drop_table('failed_emails')
    # ### end Alembic commands ###
