"""add_vrbo_code_to_properties

Revision ID: b6a81b2f0ebc
Revises: 25d5ad84efe7
Create Date: 2026-03-15 11:59:08.694676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6a81b2f0ebc'
down_revision: Union[str, Sequence[str], None] = '25d5ad84efe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('vrbo_code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_properties_vrbo_code'), 'properties', ['vrbo_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_vrbo_code'), table_name='properties')
    op.drop_column('properties', 'vrbo_code')
    # ### end Alembic commands ###
